
spring.data.mongodb.uri=${MONGODB_URI}
server.port=8080
jwt.secret=${JWT_SECRET}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile

#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.google.redirect-uri=https://voixaenglish.com/login/oauth2/code/{registrationId}

#frontend.url=http://localhost:4200
frontend.url=https://voixaenglish.com

server.forward-headers-strategy=framework

server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for

spring.cloud.aws.region.static=us-east-1

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.price-id=${STRIPE_PRICE_ID}
stripe.coupon-id=${STRIPE_COUPON_ID}